### ISSUE TITLE
pre-launch checklist

### ISSUE THREAD

**Issue by fpliger** [EuroPython/epcon#53]
List of tasks to do before launch:
- [ ] Solve Paypal redirect [#12]
- [x] Reset STRIPE from test to production 
- [x] Reset Google Social Auth [#52]
- [x] Register all sponsors and logos
- [x] Upload sponsors resized logo if app does not resize
- [ ] redirect europython.eu to ep2015.europython.eu (and configure nginx to that subdmain)
- [x] review fares and deadlines
- [ ] add missing texts at home
- [x] check helpdesk email is correctly set and visible on the app (menu?footer?)
- [x] feeds (https://dev.europython.eu/en/blog/feeds/latest/) -> 404
- [ ] set ALLOWED_HOSTS

**Comment by malemburg** [comment]
The feeds need to be changed to point to http://blog.europython.eu/rss
I already did this, but for some reason the site doesn't show these changes.

**Comment by malemburg** [comment]
Regarding helpdesk integration: there is no integration. We just point to the helpdesk email address on the contacts/ page.

It may be useful to point to this in some other places as well.

**Comment by malemburg** [comment]
RE Paypal: If stripe works, it's better to use this for payments.

Unless the Paypal account has already been used a bit, chances are high that a sudden burst in action will trigger a lock on the account. With stripe you get the money into your bank account within 7 days (without any such locks).

**Comment by fpliger** [comment]
> Regarding helpdesk integration: there is no integration. We just point to the helpdesk email address on the contacts/ page.

yes, that was what I intended to say... :-) rephrasing...

**Comment by fpliger** [comment]
FWIW I'd promote stripe over Paypal too.. specially in this first batch of tickets...

**Comment by barrachri** [comment]
RSS feeds works now.

**Comment by barrachri** [comment]
> FWIW I'd promote stripe over Paypal too.. specially in this first batch of tickets...

Good idea, we can see if some users ask for it.

**Comment by oiertwo** [comment]
I had this todo list before launch from Borja (spanish):

## HOME
- Añadir todo el texto que está vacio en el home.
- Añadir algunos quotes en la parte de /admin/
- Añadir los sponsors con su imagen en la parte /admin/
- En la imagen del home añadir enlace al email del helpdesk por ejemplo?
- El code of conduct apunta a /coc y en la lista de páginas se llama /conduct-code/ (footer)
- El imprint apunta a algo que tampoco existe, no se lo que es. (footer)

## call-proposals
- Quitar lo que pone de testing y añadir algo de texto. ¿Cerrar hasta centro de unos días la opción de CFP?
- Dentro de conference/paper-submission/ vuelve a aparecer el idioma italiano/ingles, la subcommunity otra, etc. Es lo viejo y lo que habías hecho no sale ahora mismo. 

## CALENDAR
- Está vacio, no se si podríamos poner las fechas "estimadas" para todo, como está dentro de registration, o bien desactivarlo y a cascarla.

## BLOG
- No sale nada y tampoco tengo muy claro cómo funciona, si pilla noticias de algún lado o que. Podríamos desactivarlo también.

## SPONSORS
- Podemos poner el brochure más o menos definitivo que tenemos para descargar al principio de la descripción.

**Comment by fpliger** [comment]
@oiertwo the list here was taken also from Borja list... but some of his issues seemed resolved and other were less high priority that we don't need them for the launch (i.e. the CFP)

**Comment by oiertwo** [comment]
Ok, i wrote them just in case.

**Comment by barrachri** [comment]
We need to set ALLOWED_HOSTS

**Comment by fpliger** [comment]
> We need to set ALLOWED_HOSTS

added to the list...

Also unchecked google Social Auth even if registration is down until we get the code working ok on the server

**Comment by aramboi** [comment]
Closing issue as it is not relevant any more.
